//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isetanutdbEntities : DbContext
    {
        public isetanutdbEntities()
            : base("name=isetanutdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<T_BRANCH> T_BRANCH { get; set; }
        public virtual DbSet<T_IVRLINE> T_IVRLINE { get; set; }
        public virtual DbSet<T_OFFICELINK> T_OFFICELINK { get; set; }
        public virtual DbSet<T_RTTK> T_RTTK { get; set; }
        public virtual DbSet<T_SERVER> T_SERVER { get; set; }
        public virtual DbSet<T_CALLINFO> T_CALLINFO { get; set; }
    }
}
