//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CALLINFO
    {
        public string ORG_KYOKU_NO { get; set; }
        public string ORG_STN_NO { get; set; }
        public string DEST_TEL_NO { get; set; }
        public System.DateTime REGIST_TIME { get; set; }
        public string RECFILE_PATH { get; set; }
        public string PLAY_FLG { get; set; }
        public string ANSWER_FLG { get; set; }
        public int CALL_ID { get; set; }
        public int SERVER_ID { get; set; }
    }
}
