//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IVRLINE
    {
        public int SERVER_ID { get; set; }
        public int LINE_NO { get; set; }
        public string KYOKU_NO { get; set; }
        public int IVR_TENANT_NO { get; set; }
        public string IVR_STN_NO { get; set; }
        public string REQUEUE_FLG { get; set; }
    }
}
