//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OFFICELINK
    {
        public string KYOKU_NO { get; set; }
        public string STN_NO { get; set; }
        public string OFFICELINK_NO { get; set; }
        public string USER_DEPT { get; set; }
        public string USER_NAME { get; set; }
    }
}
